package jio.codeanalysis.java.model;

public enum StatementType {
    VARIABLE_DECLARATION_STATEMENT,
    ASSERT_STATEMENT,
    BREAK_STATEMENT,
    CONSTRUCTOR_INVOCATION,
    CONTINUE_STATEMENT,
    EMPTY_STATEMENT,
    EXPRESSION_STATEMENT,
    LABELED_STATEMENT,
    RETURN_STATEMENT,
    SUPER_CONSTRUCTOR_INVOCATION,
    THROW_STATEMENT,
    TYPE_DECLARATION_STATEMENT,
    SWITCH_CASE,
    SYNCHRONIZED_STATEMENT,
    TRY_STATEMENT,
    CATCH_STATEMENT,
    FINALLY_STATEMENT,
    BLOCK_STATEMENT,
    IF_STATEMENT,
    ELSE_STATEMENT,
    SWITCH_STATEMENT,
    FOR_STATEMENT,
    WHILE_STATEMENT,
    DO_STATEMENT,
    ENHANCED_FOR_STATEMENT;
}
